[project]
name = "profix"
version = "0.1.0"
description = "Linux Steam and Proton prefix manager"
requires-python = ">=3.12"
dependencies = [
    "PyYAML>=6.0"
]

[project.scripts]
profix = "profix.main:main"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["profix*"]